// <auto-generated />
using Ecom.Backend.InfraStructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecom.Backend.InfraStructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240221131323_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecom.Backend.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "C1",
                            Name = "Category1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "C2",
                            Name = "Category2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "C3",
                            Name = "Category3"
                        });
                });

            modelBuilder.Entity("Ecom.Backend.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductPicture")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "P1",
                            Name = "Product1",
                            Price = 0m,
                            ProductPicture = "https://"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "P2",
                            Name = "Product2",
                            Price = 0m,
                            ProductPicture = "https://"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "P3",
                            Name = "Product3",
                            Price = 0m,
                            ProductPicture = "https://"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "P4",
                            Name = "Product4",
                            Price = 0m,
                            ProductPicture = "https://"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "P5",
                            Name = "Product5",
                            Price = 0m,
                            ProductPicture = "https://"
                        });
                });

            modelBuilder.Entity("Ecom.Backend.Core.Entities.Product", b =>
                {
                    b.HasOne("Ecom.Backend.Core.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Ecom.Backend.Core.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
